[phases.setup]
aptPkgs = ["python3", "python3-pip", "python3-venv"]

[phases.install]
cmd = "pip install -r backend/requirements.txt"

[start]
cmd = "cd backend && uvicorn server:app --host 0.0.0.0 --port $PORT"